# Generated by Django 3.2.16 on 2023-05-17 16:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taaktype",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("omschrijving", models.CharField(max_length=200)),
                (
                    "toelichting",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("additionele_informatie", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Taak",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("melding", models.URLField()),
                ("titel", models.CharField(max_length=100)),
                ("bericht", models.CharField(blank=True, max_length=500, null=True)),
                ("additionele_informatie", models.JSONField(default=dict)),
                (
                    "taaktype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taken_voor_taaktype",
                        to="taken.taaktype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
