# Generated by Django 3.2.16 on 2023-09-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taak",
            name="resolutie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("opgelost", "Opgelost"),
                    ("niet_opgelost", "Niet opgelost"),
                    ("geannuleerd", "Geannuleerd"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
