# Generated by Django 3.2.16 on 2023-05-25 18:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliassen", "0001_initial"),
        ("taken", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taak",
            options={
                "ordering": ("-aangemaakt_op",),
                "verbose_name": "Taak",
                "verbose_name_plural": "Taken",
            },
        ),
        migrations.AlterModelOptions(
            name="taaktype",
            options={
                "ordering": ("-aangemaakt_op",),
                "verbose_name": "Taaktype",
                "verbose_name_plural": "Taaktypes",
            },
        ),
        migrations.AlterField(
            model_name="taak",
            name="melding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taken_voor_meldingalias",
                to="aliassen.meldingalias",
            ),
        ),
        migrations.CreateModel(
            name="Taakstatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "naam",
                    models.CharField(
                        choices=[
                            ("nieuw", "Nieuw"),
                            ("bezig", "Bezig"),
                            ("voltooid", "Voltooid"),
                        ],
                        default="nieuw",
                        max_length=50,
                    ),
                ),
                (
                    "taak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taakstatussen_voor_taak",
                        to="taken.taak",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taakstatus",
                "verbose_name_plural": "Taakstatussen",
                "ordering": ("-aangemaakt_op",),
            },
        ),
        migrations.CreateModel(
            name="Taakgebeurtenis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "omschrijving_intern",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "taak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taakgebeurtenissen_voor_taak",
                        to="taken.taak",
                    ),
                ),
                (
                    "taakstatus",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taakgebeurtenis_voor_taakstatus",
                        to="taken.taakstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taakgebeurtenis",
                "verbose_name_plural": "Taakgebeurtenissen",
                "ordering": ("-aangemaakt_op",),
            },
        ),
        migrations.AddField(
            model_name="taak",
            name="taakstatus",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taak_voor_taakstatus",
                to="taken.taakstatus",
            ),
        ),
    ]
