# Generated by Django 3.2.16 on 2023-05-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taken", "0002_auto_20230525_2040"),
    ]

    operations = [
        migrations.AddField(
            model_name="taak",
            name="afgesloten_op",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taak",
            name="resolutie",
            field=models.CharField(
                choices=[("opgelost", "Opgelost"), ("niet_opgelost", "Niet opgelost")],
                default="niet_opgelost",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="taak",
            name="taakopdracht",
            field=models.URLField(default="https://example.com"),
            preserve_default=False,
        ),
    ]
