# Generated by Django 3.2.16 on 2023-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0002_alter_taak_resolutie"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktype",
            name="volgende_taaktypes",
            field=models.ManyToManyField(
                related_name="vorige_taaktypes_voor_taaktype", to="taken.Taaktype"
            ),
        ),
    ]
