# Generated by Django 3.2.16 on 2023-09-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0003_taaktype_volgende_taaktypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taaktype",
            name="volgende_taaktypes",
            field=models.ManyToManyField(
                blank=True,
                related_name="vorige_taaktypes_voor_taaktype",
                to="taken.Taaktype",
            ),
        ),
    ]
