# Generated by Django 3.2.16 on 2023-06-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taken", "0003_auto_20230531_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakgebeurtenis",
            name="gebruiker",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
