# Generated by Django 3.2.16 on 2023-10-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0004_alter_taaktype_volgende_taaktypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktype",
            name="actief",
            field=models.BooleanField(default=True),
        ),
    ]
