# Generated by Django 3.2.16 on 2023-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0005_taaktype_actief"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taakstatus",
            name="naam",
            field=models.CharField(
                choices=[
                    ("nieuw", "Nieuw"),
                    ("toegewezen", "Toegewezen"),
                    ("openstaand", "Openstaand"),
                    ("voltooid", "Voltooid"),
                ],
                default="nieuw",
                max_length=50,
            ),
        ),
    ]
