# Generated by Django 3.2.16 on 2024-02-20 17:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0007_alter_taak_resolutie"),
    ]

    operations = [
        migrations.AddField(
            model_name="taak",
            name="geometrie",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
