# Generated by Django 3.2.16 on 2024-03-05 16:40

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0008_taak_geometrie"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaakDeellink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("gedeeld_door", models.CharField(max_length=200)),
                ("signed_data", models.CharField(max_length=500, unique=True)),
                (
                    "bezoekers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(
                            blank=True, max_length=254, null=True
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "taak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taakdeellinks_voor_taak",
                        to="taken.taak",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
