# Generated by Django 3.2.18 on 2024-05-29 08:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktype", "0001_initial"),
        ("taken", "0011_taaktype_gerelateerde_onderwerpen"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktype",
            name="afdelingen",
            field=models.ManyToManyField(
                blank=True,
                related_name="taaktypes_voor_afdelingen",
                to="taaktype.Afdeling",
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="icoon",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="taaktype/icons"
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="taaktypemiddelen",
            field=models.ManyToManyField(
                blank=True,
                related_name="taaktypes_voor_taaktypemiddelen",
                to="taaktype.TaaktypeMiddel",
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="verantwoordelijke",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="taaktype",
            name="gerelateerde_onderwerpen",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), default=list, size=None
            ),
        ),
    ]
