# Generated by Django 4.2.11 on 2024-06-05 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0012_auto_20240529_1104"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taaktype",
            name="gerelateerde_onderwerpen",
        ),
        migrations.RemoveField(
            model_name="taaktype",
            name="icoon",
        ),
        migrations.RemoveField(
            model_name="taaktype",
            name="verantwoordelijke",
        ),
    ]
