# Generated by Django 4.2.11 on 2024-05-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktype", "0002_taaktypevoorbeeldsituatie_taaktype"),
        ("taken", "0012_auto_20240529_1104"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktype",
            name="afdelingen",
            field=models.ManyToManyField(
                blank=True,
                related_name="taaktypes_voor_afdelingen",
                to="taaktype.afdeling",
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="gerelateerde_taaktypes",
            field=models.ManyToManyField(
                blank=True,
                related_name="gerelateerde_taaktypes_voor_taaktype",
                to="taken.taaktype",
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="taaktypemiddelen",
            field=models.ManyToManyField(
                blank=True,
                related_name="taaktypes_voor_taaktypemiddelen",
                to="taaktype.taaktypemiddel",
            ),
        ),
    ]
