# Generated by Django 3.2.18 on 2024-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0012_auto_20240529_1104"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktype",
            name="gerelateerde_taaktypes",
            field=models.ManyToManyField(
                blank=True,
                related_name="gerelateerde_taaktypes_voor_taaktype",
                to="taken.Taaktype",
            ),
        ),
    ]
