# Generated by Django 3.2.16 on 2024-04-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktype", "0002_taaktypereden_taaktype"),
        ("taken", "0012_auto_20240403_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taaktype",
            name="taaktypemiddelen",
            field=models.ManyToManyField(
                blank=True,
                related_name="taaktypes_voor_taaktypemiddelen",
                to="taaktype.TaaktypeMiddel",
            ),
        ),
    ]
