# Generated by Django 3.2.18 on 2024-05-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0013_auto_20240515_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktype",
            name="icoon",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="taaktype/icons"
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="verantwoordelijke",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
