# Generated by Django 4.2.11 on 2024-06-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0013_remove_taaktype_gerelateerde_onderwerpen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taak",
            name="bezig_met_verwerken",
            field=models.BooleanField(default=False),
        ),
    ]
