# Generated by Django 4.2.11 on 2024-07-02 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0014_taak_bezig_met_verwerken"),
    ]

    operations = [migrations.RunSQL("CREATE EXTENSION pg_trgm;")]
