# Generated by Django 4.2.11 on 2024-07-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0015_auto_20240702_1112"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taak",
            index=models.Index(
                fields=["taakstatus"], name="taken_taak_taaksta_0e016e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taak",
            index=models.Index(
                fields=["taaktype"], name="taken_taak_taaktyp_3f8735_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taak",
            index=models.Index(
                fields=["melding"], name="taken_taak_melding_093203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taak",
            index=models.Index(
                fields=["taak_zoek_data"], name="taken_taak_taak_zo_f5dd7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taak",
            index=models.Index(
                fields=["geometrie"], name="taken_taak_geometr_cedb20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taak",
            index=models.Index(
                fields=["taakopdracht"], name="taken_taak_taakopd_47887e_idx"
            ),
        ),
    ]
