# Generated by Django 4.2.11 on 2024-07-10 11:31

from django.db import migrations, models


def move_resolutie_to_taakgebeurtenis(apps, schema_editor):
    Taak = apps.get_model("taken", "Taak")
    Taakgebeurtenis = apps.get_model("taken", "Taakgebeurtenis")
    for taak in Taak.objects.exclude(resolutie__isnull=True):
        taakgebeurtenis = Taakgebeurtenis.objects.filter(
            taak=taak, taakstatus__naam="voltooid"
        ).first()
        if taakgebeurtenis:
            taakgebeurtenis.resolutie = taak.resolutie
            taakgebeurtenis.save()


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0016_taak_taken_taak_taaksta_0e016e_idx_and_more"),
    ]

    operations = [
        # Step 1: Add the resolutie field to Taakgebeurtenis
        migrations.AddField(
            model_name="taakgebeurtenis",
            name="resolutie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("opgelost", "Opgelost"),
                    ("niet_opgelost", "Niet opgelost"),
                    ("geannuleerd", "Geannuleerd"),
                    ("niet_gevonden", "Niets aangetroffen"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        # Step 2: Data migration to move values from Taak.resolutie to Taakgebeurtenis.resolutie
        migrations.RunPython(move_resolutie_to_taakgebeurtenis),
        migrations.AlterField(
            model_name="taakstatus",
            name="naam",
            field=models.CharField(
                choices=[
                    ("nieuw", "Nieuw"),
                    ("toegewezen", "Toegewezen"),
                    ("openstaand", "Openstaand"),
                    ("voltooid", "Voltooid"),
                    ("voltooid_met_feedback", "Voltooid met feedback"),
                ],
                default="nieuw",
                max_length=50,
            ),
        ),
    ]
