# Generated by Django 4.2.11 on 2024-07-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0017_remove_taak_taken_taak_geometr_cedb20_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taakzoekdata",
            index=models.Index(
                fields=["begraafplaats"], name="taken_taakz_begraaf_a180ca_idx"
            ),
        ),
    ]
