# Generated by Django 4.2.15 on 2024-08-19 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0017_remove_taak_resolutie_taakgebeurtenis_resolutie_and_more"),
        ("taken", "0018_taakzoekdata_taken_taakz_begraaf_a180ca_idx"),
    ]

    operations = []
