# Generated by Django 4.2.15 on 2024-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0020_taak_verwijderd_op"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taaktype",
            name="toelichting",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
