# Generated by Django 4.2.15 on 2025-04-16 10:41

import django.contrib.postgres.fields
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0022_alter_taak_titel"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="taak",
            name="taken_taak_bezig_m_6e55bb_idx",
        ),
        migrations.RemoveField(
            model_name="taak",
            name="bezig_met_verwerken",
        ),
        migrations.AddField(
            model_name="taakgebeurtenis",
            name="bijlage_paden",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="taakgebeurtenis",
            name="notificatie_verstuurd",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taakgebeurtenis",
            name="vervolg_taaktypes",
            field=utils.fields.ListJSONField(default=list),
        ),
    ]
