# Generated by Django 4.2.15 on 2025-04-16 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0023_remove_taak_taken_taak_bezig_m_6e55bb_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taakgebeurtenis",
            name="bijlage_paden",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
