# Generated by Django 4.2.15 on 2025-05-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0024_alter_taakgebeurtenis_bijlage_paden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taak",
            name="bericht",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
