# Generated by Django 4.2.15 on 2025-07-17 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0025_alter_taak_bericht"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="taak",
            name="taken_taak_taak_zo_f5dd7e_idx",
        ),
    ]
