# Generated by Django 5.2.5 on 2025-10-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aliassen", "0006_meldingalias_aliassen_me_locatie_8205db_idx"),
        ("taken", "0026_remove_taak_taken_taak_taak_zo_f5dd7e_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taak",
            index=models.Index(
                fields=["aangemaakt_op"], name="taken_taak_aangema_bf6c84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taak",
            index=models.Index(
                fields=["verwijderd_op"], name="taken_taak_verwijd_d95c26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taakgebeurtenis",
            index=models.Index(
                fields=["aangemaakt_op"], name="taken_taakg_aangema_43a5a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taakstatus",
            index=models.Index(fields=["naam"], name="taken_taaks_naam_726837_idx"),
        ),
        migrations.AddIndex(
            model_name="taakstatus",
            index=models.Index(
                fields=["aangemaakt_op"], name="taken_taaks_aangema_bb145a_idx"
            ),
        ),
    ]
