# Generated by Django 5.2.5 on 2025-10-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0027_taak_taken_taak_aangema_bf6c84_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taakstatus",
            index=models.Index(
                fields=["aangemaakt_op", "naam"], name="aangemaakt_op__naam_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taakstatus",
            index=models.Index(
                fields=["naam", "aangemaakt_op"], name="naam__aangemaakt_op_idx"
            ),
        ),
    ]
