# Generated by Django 5.2.5 on 2025-10-30 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_results", "0014_alter_taskresult_status"),
        ("taken", "0028_taakstatus_aangemaakt_op__naam_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakgebeurtenis",
            name="task_taakopdracht_notificatie",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taakgebeurtenis",
                to="django_celery_results.taskresult",
            ),
        ),
    ]
