# Generated by Django 5.2.5 on 2025-11-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0029_taakgebeurtenis_task_taakopdracht_notificatie"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakgebeurtenis",
            name="notificatie_error",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
