# Generated by Django 5.2.5 on 2026-03-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliassen', '0009_meldingalias_meldingalias_buurt_begr_idx'),
        ('taken', '0030_taakgebeurtenis_notificatie_error'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taak',
            index=models.Index(condition=models.Q(('verwijderd_op__isnull', True)), fields=['melding', 'taaktype'], name='taak_melding_type_active_idx'),
        ),
    ]
