# Generated by Django 5.2.5 on 2026-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0014_alter_taskresult_status'),
        ('taken', '0031_taak_taak_melding_type_active_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taakgebeurtenis',
            index=models.Index(fields=['taak', '-aangemaakt_op'], name='taakgeb_taak_aangemaakt_idx'),
        ),
    ]
