# Generated by Django 5.2.5 on 2026-03-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taken', '0032_taakgebeurtenis_taakgeb_taak_aangemaakt_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='taakgebeurtenis',
            name='groep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
