# Generated by Django 5.2.5 on 2026-06-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taken', '0034_taakgebeurtenis_reden_afwijzing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taakgebeurtenis',
            name='reden_afwijzing_toelichting',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
