# Generated by Django 4.2.11 on 2024-06-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instellingen", "0002_instelling_mor_core_basis_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instelling",
            name="onderwerpen_basis_url",
            field=models.URLField(default="http://onderwerpen.mor.local:8006"),
        ),
    ]
