# Generated by Django 4.2.11 on 2024-07-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instellingen", "0003_instelling_onderwerpen_basis_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="instelling",
            name="email_beheer",
            field=models.EmailField(
                default="functioneelbeheerstz@rotterdam.nl", max_length=254
            ),
            preserve_default=False,
        ),
    ]
