# Generated by Django 5.2.5 on 2025-10-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instellingen", "0004_instelling_email_beheer"),
    ]

    operations = [
        migrations.AddField(
            model_name="instelling",
            name="locaties_basis_url",
            field=models.URLField(default="http://locaties.mor.local:8010"),
        ),
    ]
