# Generated by Django 3.2.18 on 2024-05-27 14:19


import django.contrib.postgres.fields
import utils.images
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0003_gebruiker_telefoonnummer"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiel",
            name="buurten",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="profiel",
            name="profielfoto",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=utils.images.get_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="profiel",
            name="werklocatie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("volledig", "volledig"),
                    ("noord", "noord"),
                    ("zuid", "Zuid"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
