# Generated by Django 3.2.18 on 2024-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktype", "0001_initial"),
        ("authenticatie", "0004_auto_20240527_1619"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfielAfdeling",
        ),
        migrations.AlterField(
            model_name="profiel",
            name="afdelingen",
            field=models.ManyToManyField(
                blank=True,
                related_name="profielen_voor_afdelingen",
                to="taaktype.Afdeling",
            ),
        ),
    ]
