# Generated by Django 3.2.18 on 2024-05-28 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0004_auto_20240527_1619"),
    ]
    operations = []
