# Generated by Django 3.2.18 on 2024-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0005_auto_20240528_1224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiel",
            name="werklocatie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("volledig", "Volledig"),
                    ("noord", "Noord"),
                    ("zuid", "Zuid"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
