# Generated by Django 3.2.18 on 2024-05-29 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0006_alter_profiel_werklocatie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profiel",
            old_name="werklocatie",
            new_name="stadsdeel",
        ),
    ]
