# Generated by Django 3.2.18 on 2024-05-29 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0007_rename_werklocatie_profiel_stadsdeel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profiel",
            old_name="buurten",
            new_name="wijken",
        ),
    ]
