# Generated by Django 4.2.11 on 2024-06-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0008_rename_buurten_profiel_wijken"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiel",
            name="onboarding_compleet",
            field=models.BooleanField(default=False),
        ),
    ]
