# Generated by Django 4.2.11 on 2024-06-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0013_remove_taaktype_gerelateerde_onderwerpen_and_more"),
        ("authenticatie", "0008_rename_buurten_profiel_wijken"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiel",
            name="taaktypes",
            field=models.ManyToManyField(
                blank=True, related_name="profielen_voor_taaktypes", to="taken.taaktype"
            ),
        ),
    ]
