# Generated by Django 4.2.11 on 2024-06-05 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0008_rename_buurten_profiel_wijken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profiel",
            name="afdelingen",
        ),
    ]
