# Generated by Django 4.2.11 on 2024-06-12 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0009_profiel_onboarding_compleet"),
        ("authenticatie", "0009_profiel_taaktypes"),
    ]

    operations = []
