# Generated by Django 4.2.11 on 2024-06-13 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0010_merge_20240612_2156"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiel",
            name="afdelingen",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
