# Generated by Django 4.2.15 on 2024-12-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0012_alter_profiel_stadsdeel"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruiker",
            name="verwijderd_op",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
