# Generated by Django 3.2.16 on 2023-12-12 14:11

import uuid

import utils.images
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReleaseNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("titel", models.CharField(max_length=255)),
                ("beschrijving", models.TextField(blank=True)),
                ("publicatie_datum", models.DateTimeField(blank=True, null=True)),
                (
                    "afbeelding",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=utils.images.get_upload_path,
                    ),
                ),
                ("versie", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
