# Generated by Django 3.2.16 on 2023-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("release_notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasenote",
            name="beschrijving",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="releasenote",
            name="versie",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
