# Generated by Django 3.2.16 on 2023-12-14 17:03

import uuid

import django.db.models.deletion
import utils.images
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("release_notes", "0002_auto_20231212_1707"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="releasenote",
            name="afbeelding",
        ),
        migrations.CreateModel(
            name="Bijlage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "bestand",
                    models.FileField(
                        max_length=255, upload_to=utils.images.get_upload_path
                    ),
                ),
                (
                    "afbeelding",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=utils.images.get_upload_path,
                    ),
                ),
                (
                    "afbeelding_verkleind",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=utils.images.get_upload_path,
                    ),
                ),
                ("mimetype", models.CharField(max_length=30)),
                ("is_afbeelding", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bijlage",
                "verbose_name_plural": "Bijlagen",
            },
        ),
    ]
