# Generated by Django 3.2.16 on 2024-02-20 17:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("release_notes", "0004_alter_releasenote_beschrijving"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasenote",
            name="bekeken_door_gebruikers",
            field=models.ManyToManyField(
                blank=True,
                related_name="bekeken_release_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="releasenote",
            name="publicatie_datum",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
