# Generated by Django 4.2.15 on 2024-09-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("release_notes", "0005_auto_20240220_1827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasenote",
            name="beschrijving",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
