# Generated by Django 3.2.16 on 2023-05-25 18:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taken", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeldingAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("bron_url", models.CharField(max_length=500)),
                (
                    "response_json",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
            ],
            options={
                "verbose_name": "Melding alias",
                "verbose_name_plural": "Melding aliassen",
            },
        ),
        migrations.CreateModel(
            name="BijlageAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("bron_url", models.CharField(max_length=500)),
                (
                    "response_json",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "taak_gebeurtenis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bijlagen_voor_taak_gebeurtenis",
                        to="taken.taak",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bijlage alias",
                "verbose_name_plural": "Bijlage aliassen",
            },
        ),
    ]
