# Generated by Django 3.2.16 on 2023-06-28 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0001_initial"),
        ("aliassen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bijlagealias",
            name="taak_gebeurtenis",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bijlagen_voor_taak_gebeurtenis",
                to="taken.taakgebeurtenis",
            ),
            preserve_default=False,
        ),
    ]
