# Generated by Django 3.2.16 on 2023-05-31 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taken", "0003_auto_20230531_1452"),
        ("aliassen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bijlagealias",
            name="taak_gebeurtenis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bijlagen_voor_taak_gebeurtenis",
                to="taken.taakgebeurtenis",
            ),
        ),
    ]
