# Generated by Django 3.2.18 on 2024-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aliassen", "0002_bijlagealias_taak_gebeurtenis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meldingalias",
            name="bron_url",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
