# Generated by Django 4.2.15 on 2025-06-02 12:26

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aliassen", "0003_alter_meldingalias_bron_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="meldingalias",
            name="begraafplaats",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="bron_signaal_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="buurtnaam",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="geometrie",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="grafnummer",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="huisletter",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="huisnummer",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="lichtmast_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="locatie_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="melding_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="plaatsnaam",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="postcode",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="straatnaam",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="thumbnail_afbeelding_relative_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="toevoeging",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="vak",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="wijknaam",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="zoek_tekst",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["straatnaam"], name="aliassen_me_straatn_0e4b54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["huisnummer"], name="aliassen_me_huisnum_7df779_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["huisletter"], name="aliassen_me_huislet_4ace1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["toevoeging"], name="aliassen_me_toevoeg_fc593f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["postcode"], name="aliassen_me_postcod_ab8513_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["geometrie"], name="aliassen_me_geometr_59e02e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["wijknaam"], name="aliassen_me_wijknaa_fed07a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["buurtnaam"], name="aliassen_me_buurtna_a48791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["begraafplaats"], name="aliassen_me_begraaf_9d6e9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["bron_signaal_ids"], name="aliassen_me_bron_si_c82a52_gin"
            ),
        ),
    ]
