# Generated by Django 4.2.15 on 2025-07-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aliassen", "0004_meldingalias_begraafplaats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meldingalias",
            name="locatie_verbose",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
