# Generated by Django 5.2.5 on 2025-10-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aliassen", "0005_meldingalias_locatie_verbose"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["locatie_verbose"], name="aliassen_me_locatie_8205db_idx"
            ),
        ),
    ]
