# Generated by Django 5.2.5 on 2025-10-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aliassen", "0006_meldingalias_aliassen_me_locatie_8205db_idx"),
        ("django_celery_results", "0014_alter_taskresult_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="meldingalias",
            name="response_status_code",
            field=models.PositiveSmallIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="meldingalias",
            name="task_update_melding_alias_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meldingalias",
                to="django_celery_results.taskresult",
            ),
        ),
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["response_status_code"], name="aliassen_me_respons_1dfe17_idx"
            ),
        ),
    ]
