# Generated by Django 5.2.5 on 2025-10-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aliassen", "0007_meldingalias_response_status_code_and_more"),
        ("django_celery_results", "0014_alter_taskresult_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="meldingalias",
            index=models.Index(
                fields=["locatie_type"], name="aliassen_me_locatie_e9f3dd_idx"
            ),
        ),
    ]
