# Generated by Django 5.2.5 on 2026-03-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliassen', '0008_meldingalias_aliassen_me_locatie_e9f3dd_idx'),
        ('django_celery_results', '0014_alter_taskresult_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meldingalias',
            index=models.Index(fields=['buurtnaam', 'begraafplaats'], name='meldingalias_buurt_begr_idx'),
        ),
    ]
