# Generated by Django 3.2.16 on 2023-08-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0001_initial"),
        ("context", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="context",
            name="filters",
        ),
        migrations.AddField(
            model_name="context",
            name="taaktypes",
            field=models.ManyToManyField(
                blank=True, related_name="contexten_voor_taaktypes", to="taken.Taaktype"
            ),
        ),
    ]
