# Generated by Django 3.2.16 on 2024-04-03 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0011_taaktype_gerelateerde_onderwerpen"),
        ("taaktype", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktypereden",
            name="taaktype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taaktyperedenen_voor_taaktype",
                to="taken.taaktype",
            ),
        ),
    ]
