# Generated by Django 4.2.11 on 2024-05-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0012_auto_20240529_1104"),
        ("taaktype", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktypevoorbeeldsituatie",
            name="taaktype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voorbeeldsituatie_voor_taaktype",
                to="taken.taaktype",
            ),
        ),
    ]
