name: Create and publish a Docker image

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  apps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build backend
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:backend"
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend

      -
        name: Build frontend
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:frontend"
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend
          
