name: 'Install, lint, test & build'

on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.10
    - name: Linting
      run: bash bin/cleanup_pre_commit.sh
    - name: Build Docker images
      run: docker compose -f docker-compose.test.yaml build --no-cache
    - name: Create Docker network
      run: docker network create behandelr_network
    - name: Start images
      run: docker compose -f docker-compose.test.yaml up
    # - name: Run Tests
      # run: docker compose -f docker-compose.test.yaml exec -T app python manage.py test
      # run: docker compose -f docker-compose.test.yaml exec -T app bash ./deploy/tests.sh
